image: nixos/unstable
environment: 
  TERM: "dumb"
  NIX_CONFIG: "experimental-features = nix-command flakes"
tasks:
- test: |
    zig version && zls --version && cd mocha
    nix develop -c zig build test -fsummary
